### ISSUE TITLE
Logged Exception ConcCalculationControlException

### ISSUE THREAD

**Issue by vidiecan** [ufal/lindat-kontext#111]
```
Message
Traceback (most recent call last):
File "/opt/kontext/deploy/source/public/../lib/controller.py", line 903, in process_method
method_ans = self._invoke_legacy_action(method, pos_args, named_args)
File "/opt/kontext/deploy/source/public/../lib/controller.py", line 529, in _invoke_legacy_action
return action(*args[1:], **na)
File "/opt/kontext/deploy/source/public/../lib/actions/concordance.py", line 262, in view
samplesize=corpus_info.sample_size)
File "/opt/kontext/deploy/source/public/../lib/controller.py", line 549, in call_function
return func(*args, **na)
File "/opt/kontext/deploy/source/public/../lib/conclib.py", line 270, in get_conc
samplesize=samplesize, fullsize=fullsize, minsize=minsize)
File "/opt/kontext/deploy/source/public/../lib/conclib.py", line 217, in _get_async_conc
raise e
ConcCalculationControlException: Unknown action: f
```

**Comment by vidiecan** [comment]
closing because we have not seen it in the latest version so far
